# Generated by Django 6.0 on 2026-01-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('image', models.ImageField(default='peoduct/default.jpg', upload_to='product')),
            ],
        ),
    ]
