# Generated by Django 6.0 on 2026-01-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/Untitled.jpg', null=True, upload_to='profiles'),
        ),
    ]
