# Generated by Django 6.0 on 2026-01-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchasing',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
