# Generated by Django 6.0 on 2026-01-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_purchasing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purchasing',
            field=models.IntegerField(),
        ),
    ]
