# Generated by Django 6.0.1 on 2026-02-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='purchasing',
        ),
    ]
