# Generated by Django 6.0.1 on 2026-02-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_purchasing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile/Untitled.jpg', null=True, upload_to='profiles'),
        ),
    ]
