# Generated by Django 6.0.1 on 2026-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/Untitled.jpg', null=True, upload_to='profiles'),
        ),
    ]
